---

- name: Create dictionary with installation variant for HANA Studio
  set_fact:
    studio: "{{ item }}"
  loop: "{{ components }}"
  when: item.component == 'hana_studio'

- name: print debug info
  debug:
    msg: "SUCCEED!"